#!/bin/bash

##############################################################################
# change the dev user's uid and gid to match the user that owns the project
# directory and run a command as that user
##############################################################################

groupmod -g $(stat -c '%g' /src) -o dev > /dev/null 2>&1
usermod -u $(stat -c '%u' /src) -o dev > /dev/null 2>&1
chown -R dev:dev ~dev/ > /dev/null 2>&1

sudo -u dev $@
